### ISSUE TITLE
If swiss.png is not there it is not being created

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/covid2019_ch_map#3]
If swiss.png is not there it is not being created
```
~/.software/covid2019_ch_map> node main.js 
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'swiss.png'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.<anonymous> (/home/zeno/.software/covid2019_ch_map/main.js:25:35)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by zdavatz** [comment]
done with: https://github.com/zdavatz/covid2019_ch_map/commit/c6195b8cb9be72b1039a4be1c37fdf3f4d7cacc4
